# Generated by Django 5.2.7 on 2025-11-11 10:42

import django.db.models.deletion
import grimoirelab.core.models
import grimoirelab.core.scheduler.models
import grimoirelab_toolkit.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_canceled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingHatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', grimoirelab.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', grimoirelab.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('uuid', models.CharField(max_length=191, unique=True)),
                ('task_type', models.CharField(max_length=128)),
                ('task_args', models.JSONField(default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'enqueued'), (3, 'running'), (4, 'completed'), (5, 'failed'), (6, 'recovery'), (7, 'canceled')], default=1)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_run', models.DateTimeField(default=None, null=True)),
                ('scheduled_at', models.DateTimeField(default=None, null=True)),
                ('job_interval', models.PositiveIntegerField(default=7200)),
                ('job_max_retries', models.PositiveIntegerField(default=5, null=True)),
                ('burst', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('affiliate', 'Affiliate'), ('unify', 'Unify'), ('genderize', 'Genderize'), ('recommend_affiliations', 'Recommend affiliations'), ('recommend_matches', 'Recommend matches'), ('recommend_gender', 'Recommend gender'), ('import_identities', 'Import identities')], max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventizerjob',
            name='job_args',
            field=models.JSONField(default=None, encoder=grimoirelab.core.scheduler.models.JobArgsEncoder, null=True),
        ),
        migrations.CreateModel(
            name='SortingHatJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', grimoirelab.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', grimoirelab.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('uuid', models.CharField(max_length=191, unique=True)),
                ('job_num', models.PositiveIntegerField()),
                ('job_args', models.JSONField(default=None, encoder=grimoirelab.core.scheduler.models.JobArgsEncoder, null=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'enqueued'), (3, 'running'), (4, 'completed'), (5, 'failed'), (6, 'recovery'), (7, 'canceled')], default=2)),
                ('progress', models.JSONField(default=None, encoder=grimoirelab.core.scheduler.models.JobResultEncoder, null=True)),
                ('logs', models.JSONField(default=None, null=True)),
                ('queue', models.CharField(default=None, max_length=128, null=True)),
                ('scheduled_at', models.DateTimeField(default=None, null=True)),
                ('started_at', models.DateTimeField(default=None, null=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tasks.sortinghattask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
